BackEnd/Models/Role.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace BackEnd.Models
{
    public class Role : IdentityRole
    {
        public Role(string name) : base(name)
        {

        }
        public virtual ICollection<ProjectRoles> ProjectRoles { get; set; }

    }
}

BackEnd/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BackEnd.Models;
using BackEnd.ViewModels.RoleViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BackEnd.Controllers
{
    [Authorize(Roles = "admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index() => View(await _roleManager.Roles.ToListAsync());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                var result = await _roleManager.CreateAsync(new IdentityRole(name));

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);

            if (role != null)
            {
                await _roleManager.DeleteAsync(role);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string userId)
        {
            if (!string.IsNullOrEmpty(userId))
            {
                var user = await _userManager.FindByIdAsync(userId);

                if (user != null)
                {
                    var userRoles = await _userManager.GetRolesAsync(user);
                    var allRoles = await _roleManager.Roles.ToListAsync();
                    var model = new ChangeRoleViewModel
                    {
                        UserId = user.Id,
                        UserEmail = user.Email,
                        UserRoles = userRoles,
                        AllRoles = allRoles
                    };
                    return View(model);
                }
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());
    }
}

BackEnd/Views/Role/Create.cshtml
@{
    ViewBag.Title = "Roles";
    Layout = "_Layout";
}

<h2>Create new role</h2>

<form method="post" asp-action="Create" asp-controller="Role">
    <div class="form-group">
        <label>Role name</label>
        <input name="Name" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Create" />
    </div>
</form>

BackEnd/Views/Role/Edit.cshtml
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore
@model BackEnd.ViewModels.RoleViewModels.ChangeRoleViewModel

@{
    ViewBag.Title = "Edit roles";
    Layout = "_Layout";
}

<h2>Edit roles for @Model.UserEmail</h2>

<form asp-action="Edit" method="post">
    <input type="hidden" name="userId" value="@Model.UserId" />
    <div class="form-group">
        @foreach (var role in Model.AllRoles)
        {
            <input type="checkbox" name="roles" value="@role.Name"
                   @(Model.UserRoles.Contains(role.Name) ? "checked=\"checked\"" : "") />@role.Name <br />
        }
    </div>
    <button type="submit" class="btn btn-primary">Sae</button>
</form>

BackEnd/Views/Role/Index.cshtml
@model System.Collections.Generic.List<Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityRole>

@{
    ViewBag.Title = "Roles";
    Layout = "_Layout";
}

<h2>System Roles</h2>

<div class="row" style="margin-bottom: 10px">
    <a asp-action="Create" class="btn btn-primary">Add role</a>
    <a asp-action="UserList" class="btn btn-primary">View User List</a>
</div>
<table class="table">
    @foreach (var role in Model)
    {
        <tr>
            <td>@role.Name</td>
            <td>
                <form asp-action="Delete" asp-route-id="@role.Id" method="post">
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </form>
            </td>
        </tr>
    }
</table>

BackEnd/Views/Role/UserList.cshtml
@model IEnumerable<BackEnd.Models.ApplicationUser>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>User list</h2>
<table class="table">
    @foreach (var user in Model)
    {
        <tr>
            <td>@user.Email</td>
            <td>
                <a class="btn btn-sm btn-primary" asp-action="Edit" asp-route-userid="@user.Id">Roles</a>
            </td>
        </tr>
    }
</table>